sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - mkdir travis-bin
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-bin/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz -O $PWD/travis-bin/geckodriver-v0.19.1-linux64.tar.gz
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -O $PWD/travis-bin/chromedriver_linux64.zip
  - tar -xvf $PWD/travis-bin/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-bin
  - cp $PWD/travis-bin/phantomjs-2.1.1-linux-x86_64/bin/phantomjs $PWD/travis-bin/
  - tar -xvf $PWD/travis-bin/geckodriver-v0.19.1-linux64.tar.gz -C $PWD/travis-bin
  - unzip $PWD/travis-bin/chromedriver_linux64.zip -d $PWD/travis-bin
  - export PATH=$PWD/travis-bin:$PATH
#  - ls -l $PWD/travis-bin
#  - chromedriver --version
#  - geckodriver --version
#  - phantomjs --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: true
script: mvn clean verify