sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - mkdir travis-bin
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-i686.tar.bz2 -O $PWD/travis-bin/phantomjs-2.1.1-linux-i686.tar.bz2
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-linux64.tar.gz -O $PWD/travis-bin/geckodriver-v0.13.0-linux64.tar.gz
  - wget https://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip -O $PWD/travis-bin/chromedriver_linux64.zip
  - tar -xvf $PWD/travis-bin/phantomjs-2.1.1-linux-i686.tar.bz2 -C $PWD/travis-bin
  - tar -xvf $PWD/travis-bin/geckodriver-v0.13.0-linux64.tar.gz -C $PWD/travis-bin
  - unzip $PWD/travis-bin/chromedriver_linux64.zip -d $PWD/travis-bin
  - export PATH=$PWD/travis-bin:$PATH
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"